# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
   - job: Build
     steps:
      - task: NuGetToolInstaller@1
        displayName: Install Nuget

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'
        displayName: Restore Nuget

      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\SchoolAPI.zip" /p:DeployIisAppPath="Default Web Site"'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
        displayName: Build Solution

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
        displayName: Publish Artifact

- stage: Dev
  dependsOn: [Build]
  jobs:
  - deployment: 
    displayName: DEV
    environment: DEV
    strategy:
     runOnce:
       deploy:
          steps:
            - download: current
              artifact: drop
            
            - task: AzureRmWebAppDeployment@4
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: 'Pay-As-You-Go(0b5d6ca7-a144-4ae7-984c-1a76c902dffe)'
                appType: 'webApp'
                WebAppName: 'xyz'
                packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
